### PR TITLE
Update cli.js to fix help text on sandbox:realm:list

### PR DESCRIPTION
**Pull request by jlbruno**
Updating sandbox:realm:list examples to include the ":list" portion.

Fix for issue #175

### CODE REVIEW

**Review by tobiaslohr — APPROVED** [review]
thanks for the contribution!

**Comment by tobiaslohr** [comment]
@jlbruno can you please update your branch from master and update the PR? I will then merge it into master

**Comment by tobiaslohr** [comment]
Fix provided in PR https://github.com/SalesforceCommerceCloud/sfcc-ci/pull/234

**Comment by jlbruno** [comment]
Thanks @tobiaslohr sorry I never saw your message, but appreciate you getting the changes merged.

**Pull request closed without merging**
