### PR TITLE
Exposes roles into the APIs level.

### PR DESCRIPTION
**Pull request by sGambolati**

### CODE REVIEW

**Comment by tobiaslohr** [comment]
Hi @sGambolati , thanks a lot for your contribution! We need you to please [sign the Salesforce.com Contributor License Agreement](https://cla.salesforce.com/sign-cla?prUrl=https%3A%2F%2Fgithub.com%2FSalesforceCommerceCloud%2Fsfcc-ci%2Fpull%2F353) in order to accept pull requests.

**Comment by tobiaslohr** [comment]
Hi @sGambolati, did you had a chance to check my comment at https://github.com/SalesforceCommerceCloud/sfcc-ci/pull/353#issuecomment-1438137406?

**Comment by sGambolati** [comment]
Hi, @tobiaslohr ! Sorry for the lack of response. I'm trying to sign up the CLA but I keep seeing this:

image

**Review by tobiaslohr — APPROVED** [review]

**Comment by tobiaslohr** [comment]
Thanks @sGambolati! I see it now. I think it just needed a re-trigger of the salesforce-cla check. Thanks for your contribution, we can merge this now.

**Pull request merged**
