### PR TITLE
Expose add cartridge to javascript

### PR DESCRIPTION
**Pull request by challmannsf**
allows to use cartridge apis via js interface

### CODE REVIEW

**Comment by tobiaslohr** [comment]
@challmannsf thanks a lot for the contribution! Can we make some updates to the docs and have the new API reflected in the README.md?

**Comment by challmannsf** [comment]
> New API should be documented in the README.md

Yes - sure, has been added

**Comment by challmannsf** [comment]
@tobiaslohr  will you take over merging ?

**Comment by ndamania-lilly** [comment]
Hello, which version takes care of the TLS1.2 issue mentioned in this KB article? https://support-demandware.force.com/customer/articles/KB_Solution/Handshake-failure-when-uploading-code-to-Staging

For those that dont have access to this KB article. I am attaching a screenshot.
image

**Comment by challmannsf** [comment]
@ndamania-lilly  I think this is related to the following repository: https://github.com/SalesforceCommerceCloud/build-suite
can you please raise your question there - I think this will lead to a quicker answer

**Pull request merged**
